# Generated by Django 4.2.11 on 2024-04-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAVStock',
            fields=[
                ('id_Stock', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SAVConso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('Date_Precedent_batch', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.savstock')),
            ],
        ),
    ]
