# Generated by Django 4.2.11 on 2024-04-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savconso',
            old_name='Date_Precedent_batch',
            new_name='date_Precedent_batch',
        ),
        migrations.RenameField(
            model_name='savstock',
            old_name='Count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='savstock',
            old_name='Name',
            new_name='name',
        ),
    ]
