# Generated by Django 4.2.11 on 2024-04-22 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0002_rename_date_precedent_batch_savconso_date_precedent_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savconso',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='savconso',
            name='date_Precedent_batch',
            field=models.DateField(default=datetime.date(2024, 4, 22)),
        ),
        migrations.AlterField(
            model_name='savstock',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
