# Generated by Django 4.2.11 on 2024-04-22 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0003_alter_savconso_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savconso',
            name='date_Precedent_batch',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
