# Generated by Django 4.2.11 on 2024-04-22 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0004_alter_savconso_date_precedent_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStock',
            fields=[
                ('id_BatchStock', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ConsoHistory',
            fields=[
                ('id_ConsoHistory', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
