# Generated by Django 4.2.11 on 2024-04-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0006_consohistory_conso_consohistory_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consohistory',
            old_name='stock',
            new_name='object',
        ),
        migrations.RemoveField(
            model_name='consohistory',
            name='conso',
        ),
    ]
