# Generated by Django 4.2.11 on 2024-04-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0008_object_rename_date_consohistory_date_conso_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savstock',
            name='name',
        ),
    ]
