# Generated by Django 4.2.11 on 2024-04-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0009_remove_savstock_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savstock',
            name='id',
        ),
        migrations.AlterField(
            model_name='savstock',
            name='id_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SAVSMapp.object'),
        ),
    ]
