# Generated by Django 4.2.11 on 2024-04-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0010_remove_savstock_id_alter_savstock_id_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consohistory',
            name='count_Conso',
        ),
        migrations.RemoveField(
            model_name='savconso',
            name='name',
        ),
        migrations.AddField(
            model_name='savstock',
            name='id_SAVStock',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='batchstock',
            name='id_object',
        ),
        migrations.RemoveField(
            model_name='consohistory',
            name='id_object',
        ),
        migrations.AlterField(
            model_name='savconso',
            name='id_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.object'),
        ),
        migrations.AlterField(
            model_name='savstock',
            name='id_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.object'),
        ),
        migrations.AddField(
            model_name='batchstock',
            name='id_object',
            field=models.ManyToManyField(to='SAVSMapp.object'),
        ),
        migrations.AddField(
            model_name='consohistory',
            name='id_object',
            field=models.ManyToManyField(to='SAVSMapp.savconso'),
        ),
    ]
