# Generated by Django 4.2.11 on 2024-04-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0011_remove_consohistory_count_conso_remove_savconso_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savconso',
            name='id',
        ),
        migrations.AddField(
            model_name='consohistory',
            name='count_Conso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savconso',
            name='id_SAVConso',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='consohistory',
            name='id_object',
        ),
        migrations.AlterField(
            model_name='savconso',
            name='id_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.object'),
        ),
        migrations.AddField(
            model_name='consohistory',
            name='id_object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.savconso'),
            preserve_default=False,
        ),
    ]
