# Generated by Django 4.2.11 on 2024-04-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0012_remove_savconso_id_consohistory_count_conso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.CharField(default='No description', max_length=500),
        ),
    ]
