# Generated by Django 4.2.11 on 2024-04-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0013_alter_object_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstock',
            name='BatchCount',
            field=models.IntegerField(default=0),
        ),
    ]
