# Generated by Django 4.2.11 on 2024-04-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0014_batchstock_batchcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savconso',
            name='id_object',
        ),
        migrations.AddField(
            model_name='savconso',
            name='id_object',
            field=models.ManyToManyField(to='SAVSMapp.object'),
        ),
    ]
