# Generated by Django 4.2.11 on 2024-04-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0015_remove_savconso_id_object_savconso_id_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consohistory',
            name='id_object',
        ),
        migrations.RemoveField(
            model_name='savconso',
            name='id_object',
        ),
        migrations.AddField(
            model_name='consohistory',
            name='id_object',
            field=models.ManyToManyField(to='SAVSMapp.savconso'),
        ),
        migrations.AddField(
            model_name='savconso',
            name='id_object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.object'),
            preserve_default=False,
        ),
    ]
