# Generated by Django 4.2.11 on 2024-04-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0017_remove_batchstock_batchcount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consohistory',
            name='id_object',
        ),
        migrations.CreateModel(
            name='ConsoHistoryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('conso_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.consohistory')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.object')),
            ],
        ),
        migrations.AddField(
            model_name='consohistory',
            name='objects',
            field=models.ManyToManyField(through='SAVSMapp.ConsoHistoryObject', to='SAVSMapp.object'),
        ),
    ]
