# Generated by Django 4.2.11 on 2024-04-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0018_remove_consohistory_id_object_consohistoryobject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consohistory',
            name='count_Conso',
        ),
    ]
