# Generated by Django 4.2.11 on 2024-04-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0019_remove_consohistory_count_conso'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstock',
            name='batchStockName',
            field=models.CharField(default='No batchStockName', max_length=50, null=True),
        ),
    ]
