# Generated by Django 4.2.11 on 2024-04-26 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0020_batchstock_batchstockname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savconso',
            options={'verbose_name': 'SAV Consumption', 'verbose_name_plural': 'SAV Consumptions'},
        ),
        migrations.RenameField(
            model_name='savconso',
            old_name='date_Precedent_Batch',
            new_name='id_Batch',
        ),
        migrations.AddField(
            model_name='savconso',
            name='date_Prece_Batch',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='batchstock',
            name='batchStockName',
            field=models.CharField(default='No BatchStock', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='savconso',
            name='id_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.object'),
        ),
    ]
