# Generated by Django 4.2.11 on 2024-04-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0021_alter_savconso_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchstock',
            options={'verbose_name': 'BatchStock', 'verbose_name_plural': 'BatchStock'},
        ),
        migrations.AlterModelOptions(
            name='batchstockobject',
            options={'verbose_name': 'BatchStockObject', 'verbose_name_plural': 'BatchStockObject'},
        ),
        migrations.AlterModelOptions(
            name='consohistory',
            options={'verbose_name': 'ConsoHistory', 'verbose_name_plural': 'ConsoHistory'},
        ),
        migrations.AlterModelOptions(
            name='consohistoryobject',
            options={'verbose_name': 'ConsoHistoryObject', 'verbose_name_plural': 'ConsoHistoryObject'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Object', 'verbose_name_plural': 'Object'},
        ),
        migrations.AlterModelOptions(
            name='savconso',
            options={'verbose_name': 'SAVConso', 'verbose_name_plural': 'SAVConso'},
        ),
        migrations.AlterModelOptions(
            name='savstock',
            options={'verbose_name': 'SAVStock', 'verbose_name_plural': 'SAVStock'},
        ),
        migrations.AlterField(
            model_name='savconso',
            name='date_Prece_Batch',
            field=models.DateField(),
        ),
    ]
