# Generated by Django 4.2.11 on 2024-04-29 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0023_alter_batchstock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchstockobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.object', unique=True),
        ),
        migrations.AlterField(
            model_name='consohistoryobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.object', unique=True),
        ),
        migrations.AlterField(
            model_name='savconso',
            name='Batch',
            field=models.ForeignKey(db_column='id_BatchStock', null=True, on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.batchstock', unique=True),
        ),
        migrations.AlterField(
            model_name='savconso',
            name='id_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.object', unique=True),
        ),
    ]
