# Generated by Django 4.2.11 on 2024-04-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0024_alter_batchstockobject_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstock',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
