# Generated by Django 4.2.11 on 2024-04-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0026_alter_batchstock_name_alter_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consohistoryobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.object'),
        ),
        migrations.AlterField(
            model_name='savconso',
            name='Batch',
            field=models.ForeignKey(db_column='id_BatchStock', null=True, on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.batchstock'),
        ),
    ]
