# Generated by Django 4.2.11 on 2024-04-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0028_alter_batchstock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savconso',
            name='id_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAVSMapp.object'),
        ),
    ]
