# Generated by Django 4.2.11 on 2024-05-06 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0029_alter_savconso_id_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savconso',
            name='Batch',
        ),
        migrations.AddField(
            model_name='consohistory',
            name='object_counts',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='savconso',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 11, 53, 0, 651895, tzinfo=datetime.timezone.utc)),
        ),
    ]
