# Generated by Django 4.2.11 on 2024-05-06 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0030_remove_savconso_batch_consohistory_object_counts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consohistoryobject',
            options={'verbose_name': 'ConsoHistoryObject', 'verbose_name_plural': 'ConsoHistoryObjects'},
        ),
        migrations.RemoveField(
            model_name='consohistory',
            name='object_counts',
        ),
        migrations.RemoveField(
            model_name='consohistory',
            name='objects',
        ),
        migrations.AlterField(
            model_name='savconso',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 12, 25, 25, 438507, tzinfo=datetime.timezone.utc)),
        ),
    ]
