# Generated by Django 4.2.11 on 2024-05-14 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAVSMapp', '0035_alter_savconso_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savconso',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 8, 4, 49, 91735, tzinfo=datetime.timezone.utc)),
        ),
    ]
