# Generated by Django 4.2.11 on 2024-05-17 11:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchStock',
            fields=[
                ('id_BatchStock', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'BatchStock',
                'verbose_name_plural': 'BatchStock',
            },
        ),
        migrations.CreateModel(
            name='ConsoHistory',
            fields=[
                ('id_ConsoHistory', models.AutoField(primary_key=True, serialize=False)),
                ('date_Conso_History', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ConsoHistory',
                'verbose_name_plural': 'ConsoHistory',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id_Object', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(default='No description', max_length=500)),
            ],
            options={
                'verbose_name': 'Object',
                'verbose_name_plural': 'Object',
            },
        ),
        migrations.CreateModel(
            name='SAVStock',
            fields=[
                ('id_SAVStock', models.AutoField(primary_key=True, serialize=False)),
                ('stock_Count', models.IntegerField(default=0)),
                ('id_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.object')),
            ],
            options={
                'verbose_name': 'SAVStock',
                'verbose_name_plural': 'SAVStock',
            },
        ),
        migrations.CreateModel(
            name='SAVConso',
            fields=[
                ('id_SAVConso', models.AutoField(primary_key=True, serialize=False)),
                ('conso_Count', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2024, 5, 17, 11, 36, 30, 825620, tzinfo=datetime.timezone.utc))),
                ('id_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.object')),
            ],
            options={
                'verbose_name': 'SAVConso',
                'verbose_name_plural': 'SAVConso',
            },
        ),
        migrations.CreateModel(
            name='ConsoHistoryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('conso_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.consohistory')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.object')),
            ],
            options={
                'verbose_name': 'ConsoHistoryObject',
                'verbose_name_plural': 'ConsoHistoryObjects',
            },
        ),
        migrations.CreateModel(
            name='BatchStockObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('batch_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.batchstock')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.object', unique=True)),
            ],
            options={
                'verbose_name': 'BatchStockObject',
                'verbose_name_plural': 'BatchStockObject',
            },
        ),
        migrations.AddField(
            model_name='batchstock',
            name='objects',
            field=models.ManyToManyField(through='panel.BatchStockObject', to='panel.object'),
        ),
    ]
