# Generated by Django 4.2.11 on 2024-05-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='localization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='pending_count',
            field=models.IntegerField(default=0),
        ),
    ]
