# Generated by Django 4.2.11 on 2024-06-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_product_localization_stock_pending_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('action_type', models.CharField(choices=[('integer', 'Integer'), ('boolean', 'Boolean')], max_length=50)),
                ('action_value', models.CharField(blank=True, max_length=50, null=True)),
                ('target_table', models.CharField(max_length=50)),
                ('target_column', models.CharField(max_length=50)),
            ],
        ),
    ]
