# Generated by Django 4.2.11 on 2024-06-06 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_shortcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='target_line',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
