# Generated by Django 4.2.11 on 2024-06-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_shortcut_target_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='action_type',
            field=models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('set', 'Set'), ('toggle', 'Toggle')], max_length=50),
        ),
    ]
